<a href="https://colab.research.google.com/github/akshithasamudrala9515/TASK_TNSIF_AI-ML/blob/main/DataCleaning%26PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}

df = pd.DataFrame(data)
df

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [2]:
# First few rows
print(df.head())
print('this is info()====================')

# Data info
print(df.info())
print('this is describe()====================')
# Summary statistics
print(df.describe())

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
this is info()====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes
None
this is describe()====================
            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

In [4]:
#Check missing values
print(df.isnull())

# Count missing values
df.isnull().sum() #count of missing values

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False  False
4   True  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False

Name    1
Age     1
City    0
dtype: int64

In [5]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [7]:
#Filling Missing Values
df["Age"] = df["Age"].fillna(df["Age"].mean())  #targeting the column
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])
#we dont have any missing values in city column

df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

In [8]:
#Selecting Multiple Columns import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Mumbai
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0  Mumbai
4  20.0  20000.0  Mumbai

In [9]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Mumbai
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0  Mumbai
4  20.00  20000.0  Mumbai

In [10]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Mumbai
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000  Mumbai
4   20   20000  Mumbai

In [11]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Mumbai
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  Mumbai
4  22.0  22000.0  Mumbai

In [12]:
df

    Age   Salary    City
0  22.0  22000.0  Mumbai
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  Mumbai
4  22.0  22000.0  Mumbai

In [13]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "MUMBAI")

df

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [14]:
df

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

ENCODING

In [15]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

    Age   Salary  City_Delhi  City_MUMBAI  City_Pune
0  22.0  22000.0       False         True      False
1  25.3  27500.0        True        False      False
2  27.5  28875.0       False        False       True
3  33.0  44000.0       False         True      False
4  22.0  22000.0       False         True      False

In [16]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI

In [17]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()

df2

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [18]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
print(df2)
df2.drop_duplicates()

   Age   Salary    City
0   22  22000.0  MUMBAI
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0  MUMBAI
4   22  22000.0  MUMBAI

   Age   Salary    City
0   22  22000.0  MUMBAI
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0  MUMBAI

In [19]:
# ==========================================
# Rainfall Dataset Cleaning
# ==========================================

# Import Libraries
import pandas as pd
import numpy as np
from google.colab import files

# Upload CSV File
uploaded = files.upload()

# Load Dataset
df = pd.read_csv("rainfall.csv")

# Display First 5 Rows
print("First 5 Rows:")
print(df.head())

# Dataset Information
print("\nDataset Info:")
print(df.info())

# ==========================================
# Convert Date Column
# ==========================================

df['date'] = pd.to_datetime(df['date'], errors='coerce')

# ==========================================
# Handle Missing Values
# ==========================================

print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())

# Fill numerical missing values with median
num_cols = ['rainfall', 'temperature', 'humidity', 'wind_speed']

for col in num_cols:
    if col in df.columns:
        df[col].fillna(df[col].median(), inplace=True)

# Fill categorical missing values with mode
df['weather_condition'].fillna(df['weather_condition'].mode()[0], inplace=True)

# Drop rows where date is missing
df.dropna(subset=['date'], inplace=True)

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

# ==========================================
# Fix Text Inconsistencies
# ==========================================

df['weather_condition'] = (
    df['weather_condition']
    .str.strip()
    .str.lower()
    .str.capitalize()
)

print("\nUnique Weather Conditions:")
print(df['weather_condition'].unique())

# ==========================================
# Remove Duplicate Rows
# ==========================================

print("\nDuplicate Rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

# ==========================================
# Convert Data Types
# ==========================================

df['rainfall'] = pd.to_numeric(df['rainfall'], errors='coerce')
df['temperature'] = pd.to_numeric(df['temperature'], errors='coerce')
df['humidity'] = pd.to_numeric(df['humidity'], errors='coerce')
df['wind_speed'] = pd.to_numeric(df['wind_speed'], errors='coerce')

# ==========================================
# Detect and Remove Outliers (IQR Method)
# ==========================================

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

print("\nDataset Shape After Removing Outliers:")
print(df.shape)

# ==========================================
# Final Clean Dataset
# ==========================================

print("\nFinal Dataset:")
print(df.head())

print("\nFinal Dataset Info:")
print(df.info())

# ==========================================
# Save Cleaned Dataset
# ==========================================

df.to_csv("cleaned_rainfall.csv", index=False)

print("\nCleaned dataset saved as 'cleaned_rainfall.csv'")

# Download the cleaned file
files.download("cleaned_rainfall.csv")

Saving rainfall.csv to rainfall.csv
First 5 Rows:
         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             Rainy
1  2022-01-02       8.2         17.8      65.0         5.2             Rainy
2  2022-01-03       0.0         20.1      52.0         3.1             Sunny
3  2022-01-04       3.7         18.6      71.0         6.7             Rainy
4  2022-01-05      21.1         14.8      82.0         9.3             Rainy

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB
None

Missing Values Before Cleaning:
date                 1
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

Missing Values After Cleaning:
date                 0
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

Unique Weather Conditions:
['Rainy' 'Sunny']

Duplicate Rows: 0

Dataset Shape After Removing Outliers:
(53, 6)

Final Dataset:
        date  rainfall  temperature  humidity  wind_speed weather_condition
0 2022-01-01      12.5         15.2      78.0         8.5             Rainy
1 2022-01-02       8.2         17.8      65.0         5.2             Rainy
2 2022-01-03       0.0         20.1      52.0         3.1             Sunny
3 2022-01-04       3.7         18.6      71.0         6.7             Rainy
4 2022-01-05      21.1         14.8      82.0         9.3             Rainy

Final Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.9+ KB
None

Cleaned dataset saved as 'cleaned_rainfall.csv'

/tmp/ipykernel_7578/717439419.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_7578/717439419.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weather_condition'].fillna(df['weather_condition'].mode()[0], inplace=True)

In [20]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.9+ KB

In [21]:
import pandas as pd

# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

date                 0
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

In [22]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             rainy
1  2022-01-02       8.2         17.8      65.0         5.2             rainy
2  2022-01-03       0.0         20.1      52.0         3.1             sunny
3  2022-01-04       3.7         18.6      71.0         6.7             rainy
4  2022-01-05      21.1         14.8      82.0         9.3             rainy
5  2022-01-06      15.3         16.5      75.0         7.8             rainy
6  2022-01-07       6.8         19.2      61.0         4.5             rainy
7  2022-01-08       0.0         21.7      48.0         2.9             sunny
8  2022-01-09      11.2         17.3      73.0         6.1             rainy
9  2022-01-10      18.6         15.8      79.0         8.9             rainy
10 2022-01-11       9.5         16.2      72.0         5.7             rainy
11 2022-01-12       2.1         19.8      58.0         3.5             rainy
12 2022-01-13       0.0         22.4      45.0         2.1             sunny
13 2022-01-14       7.4         17.9      69.0         6.5             rainy
14 2022-01-15      14.9         15.1      81.0         8.7             rainy
15 2022-01-16      19.2         16.8      77.0         7.2             rainy
16 2022-01-17       5.6         18.5      63.0         4.9             rainy
17 2022-01-18       0.0         21.2      51.0         3.3             sunny
18 2022-01-19      10.8         17.6      75.0         6.7             rainy
19 2022-01-20      16.3         14.5      84.0         9.1             rainy
20 2022-01-21       3.9         16.1      71.0         5.3             rainy
21 2022-01-22       0.0         19.4      59.0         4.1             sunny
22 2022-01-23       7.1         18.2      67.0         7.1             rainy
23 2022-01-24      12.7         15.7      79.0         8.3             rainy
24 2022-01-25      18.4         17.1      76.0         6.8             rainy
25 2022-01-26       9.8         19.7      62.0         4.7             rainy
26 2022-01-27       0.0         22.9      47.0         2.5             sunny
27 2022-01-28       6.2         18.5      70.0         7.3             rainy
28 2022-01-29      15.5         14.2      83.0         9.5             rainy
29 2022-01-30      21.8         16.4      78.0         7.6             rainy
30 2022-01-31      11.6         19.1      65.0         5.1             rainy
31 2022-02-01       0.0         21.6      53.0         3.7             sunny
32 2022-02-02       4.3         17.2      73.0         7.5             rainy
33 2022-02-03       9.1         15.4      81.0         8.9             rainy
34 2022-02-04      17.9         16.7      77.0         6.2             rainy
35 2022-02-05       7.5         18.9      64.0         4.3             rainy
36 2022-02-06       0.0         22.1      49.0         2.7             sunny
37 2022-02-07       5.8         17.8      72.0         6.9             rainy
38 2022-02-08      13.2         14.7      85.0         9.3             rainy
39 2022-02-09      19.6         16.2      79.0         7.8             rainy
40 2022-02-10      10.4         19.5      66.0         5.5             rainy
41 2022-02-11       0.0         23.4      44.0         3.1             sunny
42 2022-02-12       6.7         18.1      74.0         7.7             rainy
43 2022-02-13      14.8         13.9      87.0         9.9             rainy
44 2022-02-14      20.5         15.6      81.0         8.2             rainy
45 2022-02-15       8.3         19.2      68.0         6.1             rainy
46 2022-02-16       0.0         22.7      51.0         4.5             sunny
47 2022-02-17       5.1         17.4      75.0         8.3             rainy
48 2022-02-18      11.9         14.1      89.0        10.5             rainy
49 2022-02-19      17.3         15.9      83.0         8.6             rainy
50 2022-02-20       9.6         18.6      71.0         6.7             rainy
51 2022-02-21       0.0         21.3      55.0         5.1             sunny
52 2022-02-22       7.4         16.8      77.0         8.9             rainy